---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
  armv7: ghcr.io/hassio-addons/debian-base/armv7:stable
  i386: ghcr.io/hassio-addons/debian-base/i386:stable
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
